---
#
# Ansible tasks for the vault role
#

# @TODO a HEAD call would be ideal here to determine if exists

# Watch this for memory issues if the number of secrets > 1000
- name: secret - Get the current secrets
  uri:
    url: "{{ vault_base_url }}/v1/{{ item.path }}"
    method: GET
    status_code: "200,404"
    validate_certs: "{{ vault_api_validate_certs }}"
    headers:
      X-Vault-Token: "{{ vault_token }}"
  with_items: "{{ vault_secret_config | default([]) }}"
  no_log: true
  register: vault_secret_current_secrets

# Note: This will not work with jinja2 versions before 2.8.0.
# Ansible 2.1.1.0-1.el7 uses 2.7.2.
- name: secret - Determine which secrets are updateable
  set_fact:
    vault_secret_paths_found: "{{ vault_secret_current_secrets.results | selectattr('status', 'equalto', 200) | map(attribute='item.path') | list }}"
    vault_secret_paths_not_found: "{{ vault_secret_current_secrets.results | selectattr('status', 'equalto', 404) | map(attribute='item.path') | list }}"

# This will not overwrite any existing secrets
- name: secret - Ensure the secrets are present
  uri:
    url: "{{ vault_base_url }}/v1/{{ item.path }}"
    method: POST
    status_code: 204
    validate_certs: "{{ vault_api_validate_certs }}"
    headers:
      X-Vault-Token: "{{ vault_token }}"
    body_format: json
    body: "{{ item.payload }}"
  no_log: true
  with_items: "{{ vault_secret_config | default([]) }}"
  when: ( item.path in vault_secret_paths_not_found )

# @TODO Provide a way to force update of all secrets

# @TODO Provide a way for an operator to set secrets interactively
